// Workflow sources ported from agent-b's digest-bound Lex completion artifacts.
import sdkPackage from "../package.json" with { type: "json" };
const { version } = sdkPackage;

export function githubWorkflows(logDirectory) {
  const prefix = logDirectory === "." ? "" : `${logDirectory}/`;
  return Object.fromEntries(Object.entries(templates).map(([name, source]) => [
    `.github/workflows/engram-${name}.yml`,
    source.replaceAll("__SDK_VERSION__", version)
      .replaceAll("__LOG_DIR__", logDirectory)
      .replaceAll("__LOG_PREFIX__", prefix)
      .replaceAll("__LOG_REGEX__", prefix.replaceAll(".", "\\.").replaceAll("/", "\\/")),
  ]));
}

const templates = {
  "turns": [
    "name: EngramPort turn issues",
    "",
    "on:",
    "  push:",
    "    branches: [main]",
    "",
    "permissions:",
    "  contents: read",
    "  issues: write",
    "",
    "concurrency:",
    "  group: engram-turn-issues",
    "  cancel-in-progress: false",
    "",
    "jobs:",
    "  turns:",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 10",
    "    steps:",
    "      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4",
    "        with:",
    "          ref: main",
    "          fetch-depth: 1",
    "      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4",
    "        with:",
    "          node-version: '22.13.0'",
    "      - name: Install exact SDK version",
    "        working-directory: \"__LOG_DIR__\"",
    "        run: npm install --no-save --package-lock=false --ignore-scripts --no-audit --no-fund --prefix . @engramport/sdk@__SDK_VERSION__",
    "      - name: Reconcile turn issues",
    "        working-directory: \"__LOG_DIR__\"",
    "        env:",
    "          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
    "          GH_REPO: ${{ github.repository }}",
    "        run: |",
    "          node --input-type=module <<'NODE'",
    "          // BEGIN TURN LOGIC: exercised verbatim by the SDK team-kit controls.",
    "          import { readdirSync, readFileSync } from 'node:fs';",
    "          import { execFileSync } from 'node:child_process';",
    "          const run = (command, args) => execFileSync(process.env.ENGRAM_EXEC_SHIM ? process.execPath : command, process.env.ENGRAM_EXEC_SHIM ? [process.env.ENGRAM_EXEC_SHIM, command, ...args] : args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();",
    "          const gh = (...args) => run('gh', args);",
    "          const repo = process.env.GH_REPO;",
    "          if (!/^[A-Za-z0-9_.-]+\\/[A-Za-z0-9_.-]+$/.test(repo ?? '')) throw new Error('Invalid GH_REPO');",
    "          const seats = [];",
    "          for (const name of readdirSync('actors').filter(name => name.endsWith('.yaml')).sort()) {",
    "            const text = readFileSync(`actors/${name}`, 'utf8');",
    "            const fields = text.split(/\\r?\\n/).filter(line => /^github:/.test(line));",
    "            if (!/^kind:\\s*human\\s*$/m.test(text) || !fields.length) continue;",
    "            const login = fields[0].slice('github:'.length).trim();",
    "            const slug = text.match(/^slug:\\s*([^\\s]+)\\s*$/m)?.[1];",
    "            if (fields.length !== 1 || !/^[A-Za-z0-9](?:[A-Za-z0-9-]{0,37}[A-Za-z0-9])?$/.test(login) || login.includes('--')) throw new Error(`Invalid github login in ${name}`);",
    "            if (!/^[a-z0-9][a-z0-9._-]{0,127}$/.test(slug ?? '') || name !== `${slug}.yaml`) throw new Error(`Invalid actor in ${name}`);",
    "            const output = run(process.execPath, ['node_modules/@engramport/sdk/dist/cli.mjs', 'inbox', '--actor', slug]);",
    "            const paths = output === \"\" ? [] : output.split(/\\r?\\n/);",
    "            if (paths.some(path => !/^events\\/[a-z0-9][a-z0-9._-]*\\/[A-Za-z0-9._-]+\\.md$/.test(path))) throw new Error(`Unexpected inbox output for ${slug}`);",
    "            seats.push({ slug, login, paths: [...new Set(paths)].sort() });",
    "          }",
    "          // Resolve every inbox before making a write. A failed read is never a clear seat.",
    "          const pages = JSON.parse(gh('api', '--method', 'GET', '--paginate', '--slurp', `repos/${repo}/issues?state=open&per_page=100`));",
    "          const issues = pages.flat().filter(issue => !issue.pull_request);",
    "          for (const { slug, login, paths } of seats) {",
    "            const title = `Your turn: ${slug}`;",
    "            const matches = issues.filter(issue => issue.title === title).sort((a, b) => a.number - b.number);",
    "            if (!paths.length) {",
    "              for (const issue of matches) gh('issue', 'close', String(issue.number), '--repo', repo);",
    "              continue;",
    "            }",
    "            const body = [`Open EngramPort turns for @${login}:`, '', ...paths.map(path => `- \\`__LOG_PREFIX__${path}\\``), '', 'Comment here to reply as this human seat. For multiple turns include reply: EVENT_ID; optionally next: ACTOR. This issue follows the open inbox on pushes to main.'].join('\\n');",
    "            if (matches.length) {",
    "              const issue = matches[0];",
    "              const assignees = issue.assignees.map(actor => actor.login);",
    "              if (issue.body !== body || !assignees.includes(login) || assignees.length !== 1) {",
    "                const args = ['issue', 'edit', String(issue.number), '--repo', repo, '--body', body, '--add-assignee', login];",
    "                for (const previous of assignees.filter(value => value !== login)) args.push('--remove-assignee', previous);",
    "                gh(...args);",
    "              }",
    "              for (const duplicate of matches.slice(1)) gh('issue', 'close', String(duplicate.number), '--repo', repo);",
    "            } else {",
    "              gh('issue', 'create', '--repo', repo, '--title', title, '--body', body, '--assignee', login);",
    "            }",
    "          }",
    "          // END TURN LOGIC",
    "          NODE",
  ].join("\n") + "\n",
  "replies": [
    "name: EngramPort human replies",
    "",
    "on:",
    "  issue_comment:",
    "    types: [created]",
    "",
    "permissions:",
    "  contents: write",
    "  issues: write",
    "",
    "concurrency:",
    "  group: engram-reply-${{ github.event.comment.id }}",
    "  cancel-in-progress: false",
    "",
    "jobs:",
    "  reply:",
    "    if: github.event.issue.pull_request == null && github.event.comment.user.type != 'Bot'",
    "    runs-on: ubuntu-latest",
    "    timeout-minutes: 10",
    "    steps:",
    "      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4",
    "        with:",
    "          ref: main",
    "          fetch-depth: 1",
    "      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4",
    "        with:",
    "          node-version: '22.13.0'",
    "      - name: Install exact SDK version",
    "        working-directory: \"__LOG_DIR__\"",
    "        run: npm install --no-save --package-lock=false --ignore-scripts --no-audit --no-fund --prefix . @engramport/sdk@__SDK_VERSION__",
    "      - name: Bind comment and publish reply",
    "        working-directory: \"__LOG_DIR__\"",
    "        env:",
    "          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}",
    "          GH_REPO: ${{ github.repository }}",
    "        run: |",
    "          node --input-type=module <<'NODE'",
    "          // BEGIN REPLY LOGIC",
    "          import { readFileSync, existsSync } from 'node:fs';",
    "          import { execFileSync } from 'node:child_process';",
    "          import { createClient } from '@engramport/sdk';",
    "          const run = (cmd, args) => execFileSync(process.env.ENGRAM_EXEC_SHIM ? process.execPath : cmd, process.env.ENGRAM_EXEC_SHIM ? [process.env.ENGRAM_EXEC_SHIM, cmd, ...args] : args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();",
    "          const gh = (...args) => run('gh', args);",
    "          const repo = process.env.GH_REPO;",
    "          if (!/^[A-Za-z0-9_.-]+\\/[A-Za-z0-9_.-]+$/.test(repo ?? '')) throw Error('Invalid repository');",
    "          const payload = JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8'));",
    "          const { issue, comment } = payload;",
    "          if (payload.action !== 'created' || issue?.pull_request || comment?.user?.type === 'Bot') process.exit(0);",
    "          const slug = issue?.title?.match(/^Your turn: ([a-z0-9][a-z0-9._-]{0,127})$/)?.[1];",
    "          if (!slug) process.exit(0);",
    "          if (!Number.isSafeInteger(issue.number) || issue.number < 1 || !Number.isSafeInteger(comment?.id) || comment.id < 1) throw Error('Invalid issue/comment id');",
    "          const refuse = reason => { gh('issue', 'comment', String(issue.number), '--repo', repo, '--body', `Reply refused for comment ${comment.id}: ${reason}`); process.exit(0); };",
    "          const actorPath = `actors/${slug}.yaml`;",
    "          if (!existsSync(actorPath)) refuse('unknown seat');",
    "          const actor = readFileSync(actorPath, 'utf8');",
    "          const logins = [...actor.matchAll(/^github:\\s*([^\\s]+)\\s*$/gm)].map(m => m[1]);",
    "          const login = comment.user?.login;",
    "          if (!/^kind:\\s*human\\s*$/m.test(actor) || logins.length !== 1 || typeof login !== 'string' || logins[0].toLowerCase() !== login.toLowerCase()) refuse('commenter does not match the recorded human login');",
    "          try {",
    "            const refuse = reason => { throw new Error(reason); };",
    "            if (typeof comment.body !== 'string' || !comment.body.trim()) refuse('empty body');",
    "            const client = createClient({ actor: slug, cwd: process.cwd() });",
    "            const inbox = await client.inbox({ entries: true });",
    "            const named = [...(issue.body ?? '').matchAll(/`__LOG_REGEX__(events\\/[a-z0-9._-]+\\/[A-Za-z0-9._-]+\\.md)`/g)].map(m => m[1]);",
    "            const replyLines = comment.body.split(/\\r?\\n/).filter(line => /^reply:/.test(line));",
    "            const nextLines = comment.body.split(/\\r?\\n/).filter(line => /^next:/.test(line));",
    "            if (replyLines.length > 1 || nextLines.length > 1) refuse('duplicate routing directives');",
    "            const replyId = replyLines[0]?.match(/^reply: ([0-9a-f-]{36})$/)?.[1];",
    "            const nextSlug = nextLines[0]?.match(/^next: ([a-z0-9][a-z0-9._-]{0,127})$/)?.[1];",
    "            if ((replyLines.length && !replyId) || (nextLines.length && !nextSlug)) refuse('malformed routing directive');",
    "            const candidates = inbox.filter(entry => named.includes(entry.relative) && (!replyId || entry.event_id === replyId));",
    "            if (candidates.length !== 1) refuse('name exactly one currently open issue turn with reply: EVENT_ID');",
    "            const parent = candidates[0];",
    "            const next = nextSlug ?? parent.from;",
    "            if (next === 'null' || !existsSync(`actors/${next}.yaml`)) refuse('next must name a registered actor');",
    "            const trailer = `GitHub authorship binding: ${repo}#${issue.number}; comment ${comment.id}; login ${login}.`;",
    "            const result = await client.append({ thread: parent.thread, type: 'reply', reply: parent.event_id, next, body: comment.body + '\\n\\n' + trailer });",
    "            if (!result.ok) refuse(`SDK rejected reply: ${(result.errors ?? []).join('; ')}`);",
    "            await client.inbox(); // Verify the appended log before publication.",
    "            run('git', ['add', '--', result.relative]);",
    "            run('git', ['-c', 'user.name=github-actions[bot]', '-c', 'user.email=41898282+github-actions[bot]@users.noreply.github.com', 'commit', '-m', `coordination: reply to issue #${issue.number} comment ${comment.id}`]);",
    "            run('git', ['push', 'origin', 'HEAD:main']);",
    "            gh('issue', 'comment', String(issue.number), '--repo', repo, '--body', `Recorded comment ${comment.id} as __LOG_PREFIX__${result.relative}.`);",
    "          } catch (error) {",
    "            gh('issue', 'comment', String(issue.number), '--repo', repo, '--body', `Not recorded for comment ${comment.id}: ${error.message}. Comment again.`);",
    "            process.exitCode = 1;",
    "          }",
    "          // END REPLY LOGIC",
    "          NODE",
  ].join("\n") + "\n"
};
