import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const migration=await readFile(new URL("../migrations/0001_canonical_core.sql",import.meta.url),"utf8");
const issuerMigration=await readFile(new URL("../migrations/0023_founder_authorization_issuer.sql",import.meta.url),"utf8");
const observationMigration=await readFile(new URL("../migrations/0024_observation_disposition.sql",import.meta.url),"utf8");
const roles=await readFile(new URL("../deploy/init-roles.sql",import.meta.url),"utf8");
const databaseTest=await readFile(new URL("failure/app-role-grants.sql",import.meta.url),"utf8");
const issuerTest=await readFile(new URL("failure/founder-enrollment-issuer.sql",import.meta.url),"utf8");
const runner=await readFile(new URL("../scripts/run-db-tests",import.meta.url),"utf8");

test("app role has no blanket all-table grant",()=>{assert.doesNotMatch(migration,/GRANT\s+SELECT\s*,\s*INSERT\s+ON\s+ALL\s+TABLES[^;]+engram_app/i);});
test("app writes are limited to canonical append tables",()=>{assert.match(migration,/GRANT\s+INSERT\s+ON\s+events\s*,\s*event_recipients\s+TO\s+engram_app/i);for(const table of ["principals","projects","project_memberships","actors","actor_delegations","agent_sessions","threads"])assert.doesNotMatch(migration,new RegExp(`GRANT[^;]*INSERT[^;]*ON[^;]*\\b${table}\\b[^;]*TO\\s+engram_app`,"i"));});
test("app retains explicit reads needed by RLS and delegation trigger",()=>{const grant=migration.match(/GRANT\s+SELECT\s+ON\s+([^;]+)\s+TO\s+engram_app/i)?.[1]??"";for(const table of ["tenants","principals","projects","project_memberships","actors","actor_delegations","agent_sessions","threads","events","event_recipients"])assert.match(grant,new RegExp(`\\b${table}\\b`));});
test("maintenance remains separate authorization writer",()=>{assert.match(migration,/GRANT\s+SELECT\s*,\s*INSERT\s*,\s*UPDATE\s*,\s*DELETE\s+ON\s+ALL\s+TABLES[^;]+engram_maintenance/i);});
test("future database controls assert exact permission errors and positive paths",()=>{for(const table of ["actor_delegations","project_memberships","actors","principals"])assert.match(databaseTest,new RegExp(`'42501', 'permission denied for table ${table}'`));assert.match(databaseTest,/PASS app valid event INSERT/);assert.match(databaseTest,/PASS maintenance identity and authorization INSERT controls/);assert.match(databaseTest,/ROLLBACK;/);});
test("database runner executes grant controls after postgres seed",()=>{assert.match(runner,/deploy\/seed\.sql[\s\S]*tests\/failure\/app-role-grants\.sql[\s\S]*tests\/failure\/constraints\.sql/);assert.match(runner,/-U postgres -d engramport < "\$root_dir\/deploy\/seed\.sql"/);});
test("founding issuer is a dormant dedicated-role capability",()=>{assert.match(roles,/CREATE ROLE engram_bootstrap_operator NOLOGIN NOSUPERUSER NOBYPASSRLS/);assert.match(issuerMigration,/SECURITY DEFINER[\s\S]*GRANT EXECUTE[^;]+TO engram_bootstrap_operator/i);assert.match(issuerMigration,/REVOKE ALL[^;]+FROM PUBLIC,engram_app,engram_maintenance/i);assert.doesNotMatch(issuerMigration,/INSERT INTO\s+(?:public\.)?founder_external_identities/i);assert.doesNotMatch(issuerMigration,/p_(?:issuer|subject)\b/i);});
test("founding issuer refusal has a live app-role proof",()=>{assert.match(issuerTest,/SET LOCAL ROLE engram_app[\s\S]*WHEN insufficient_privilege/);assert.match(issuerTest,/SET LOCAL ROLE engram_bootstrap_operator[\s\S]*SELECT issue_founding_authorization/);assert.match(runner,/0023_founder_authorization_issuer\.sql[\s\S]*tests\/failure\/founder-enrollment-issuer\.sql/);});
test("observation disposition is private, forced-RLS, append-only, and function mediated",()=>{for(const table of ["observation_subscriptions","observation_checkpoints"])assert.match(observationMigration,new RegExp(`ALTER TABLE ${table} FORCE ROW LEVEL SECURITY`));assert.match(observationMigration,/database_role=session_user::name/);assert.match(observationMigration,/OBSERVATION_CHECKPOINT_APPEND_ONLY/);assert.match(observationMigration,/UNIQUE \(subscription_id, delivery_id\)/);assert.match(observationMigration,/REVOKE ALL ON observation_subject_bindings,observation_subscriptions,observation_checkpoints FROM PUBLIC,engram_app,engram_maintenance/);assert.match(runner,/0024_observation_disposition\.sql[\s\S]*port-watch-observation-live\.test\.mjs/);});
