import assert from "node:assert/strict";
import {spawn} from "node:child_process";
import {lstat,mkdtemp,rm,stat,writeFile} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

const root=path.resolve(new URL("..",import.meta.url).pathname),scripts={database:path.join(root,"scripts/run-db-tests"),mutation:path.join(root,"scripts/run-d1-mutation-harness")};
const pause=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
async function waitFor(file){for(let attempt=0;attempt<300;attempt++){try{await stat(file);return;}catch{await pause(10);}}throw new Error(`timed out waiting for ${file}`);}
function launch(script,args,lockPath){const child=spawn("bash",[script,...args],{cwd:root,env:{...process.env,ENGRAMPORT_DB_TEST_LOCK_PATH:lockPath},stdio:["ignore","pipe","pipe"]});let stdout="",stderr="";child.stdout.on("data",chunk=>stdout+=chunk);child.stderr.on("data",chunk=>stderr+=chunk);const completed=new Promise(resolve=>child.on("close",(code,signal)=>resolve({code,signal,stdout,stderr})));return {child,completed};}

test("both database entrypoints refuse a concurrent caller and leave the holder unaffected",async()=>{const temporary=await mkdtemp(path.join(os.tmpdir(),"engramport-lock-")),lockPath=path.join(temporary,"db.lock"),children=[];try{for(const [holderName,contenderName] of [["database","mutation"],["mutation","database"]]){const ready=path.join(temporary,`${holderName}-ready`),release=path.join(temporary,`${holderName}-release`),holder=launch(scripts[holderName],["--lock-probe",ready,release],lockPath);children.push(holder.child);await waitFor(ready);const contender=launch(scripts[contenderName],["--lock-probe",`${ready}-contender`,`${release}-contender`],lockPath),refused=await contender.completed;assert.equal(refused.code,75);assert.match(refused.stderr,/ENGRAMPORT_DB_TEST_LOCKED: .* refused; active pid=/);await writeFile(release,"");const survived=await holder.completed;assert.equal(survived.code,0);assert.match(survived.stdout,new RegExp(`ENGRAMPORT_DB_TEST_LOCK_PROBE_COMPLETED: run-${holderName==="database"?"db-tests":"d1-mutation-harness"}`));}}finally{for(const child of children)child.kill("SIGKILL");await rm(temporary,{recursive:true,force:true});}});

test("a SIGKILL-stale lock is recovered by the other entrypoint",async()=>{const temporary=await mkdtemp(path.join(os.tmpdir(),"engramport-stale-lock-")),lockPath=path.join(temporary,"db.lock"),ready=path.join(temporary,"ready"),release=path.join(temporary,"release");let holder;try{holder=launch(scripts.database,["--lock-probe",ready,release],lockPath);await waitFor(ready);holder.child.kill("SIGKILL");const killed=await holder.completed;assert.equal(killed.signal,"SIGKILL");assert.equal((await lstat(lockPath)).isSymbolicLink(),true);await writeFile(release,"");const recovery=launch(scripts.mutation,["--lock-probe",`${ready}-recovered`,release],lockPath),recovered=await recovery.completed;assert.equal(recovered.code,0);assert.match(recovered.stderr,/ENGRAMPORT_DB_TEST_LOCK_STALE_RECOVERED: prior pid=/);assert.match(recovered.stdout,/ENGRAMPORT_DB_TEST_LOCK_PROBE_COMPLETED: run-d1-mutation-harness/);await assert.rejects(()=>lstat(lockPath),error=>error.code==="ENOENT");}finally{holder?.child.kill("SIGKILL");await rm(temporary,{recursive:true,force:true});}});
