import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { FileWatchStore, PortWatch, RecordingRunner, authorizedInboxSource, decideWatch, nextPollDelay } from "../packages/port-watch/src/index.mjs";

async function fixture(view=[]){const dir=await mkdtemp(path.join(os.tmpdir(),"port-watch-")),store=new FileWatchStore(path.join(dir,"watch.json")),runner=new RecordingRunner();let authorized=[...view];const inbox=authorizedInboxSource(async({after})=>authorized.filter(e=>e.project_seq>after));const watch=new PortWatch({store,inbox,runner,supervisor_scopes:["admin:project","events:write"]});return {dir,store,runner,watch,setEvents:v=>authorized=[...v]};}
const handoff=(seq=1)=>({event_id:`event-${seq}`,project_seq:seq,kind:"handoff",addressed:true,implementation_authority:true});
async function cleanup(f){await rm(f.dir,{recursive:true,force:true});}

test("unchanged authorized inbox invokes runner exactly zero times across many ticks",async()=>{const f=await fixture();try{await f.watch.configure("agent","project",{enabled:true,scopes:["events:write"]});for(let i=0;i<100;i++)assert.deepEqual(await f.watch.tick("agent","project"),{action:"skip",reason:"unchanged"});assert.equal(f.runner.invocations.length,0);const state=await f.store.read();assert.equal(state.events.filter(e=>e.kind==="watch.polled").length,100);}finally{await cleanup(f);}});
test("unauthorized event causes zero wakes; same authorized handoff wakes exactly once",async()=>{const f=await fixture();try{await f.watch.configure("agent","project",{enabled:true,scopes:["events:write"]});f.setEvents([]);assert.equal((await f.watch.tick("agent","project")).reason,"unchanged");assert.equal(f.runner.invocations.length,0);f.setEvents([handoff()]);assert.equal((await f.watch.tick("agent","project")).action,"wake");assert.equal(f.runner.invocations.length,1);}finally{await cleanup(f);}});
test("addressed decision grants no implementation authority; eligible handoff does",async()=>{const f=await fixture([{event_id:"decision-1",project_seq:1,kind:"decision",addressed:true,implementation_authority:false}]);try{await f.watch.configure("agent","project",{enabled:true,scopes:["events:write"]});assert.equal((await f.watch.tick("agent","project")).reason,"no_eligible_handoff");assert.equal(f.runner.invocations.length,0);f.setEvents([handoff(2)]);assert.equal((await f.watch.tick("agent","project")).action,"wake");assert.equal(f.runner.invocations.length,1);}finally{await cleanup(f);}});
test("waking grants exactly actor scopes and never supervisor scopes",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project",{enabled:true,scopes:["events:write"]});await f.watch.tick("agent","project");assert.deepEqual(f.runner.invocations[0].token.scopes,["events:write"]);assert.equal(f.runner.invocations[0].token.scopes.includes("admin:project"),false);assert.deepEqual(f.runner.invocations[0].context.event_ids,["event-1"]);}finally{await cleanup(f);}});
test("cursor advances atomically only on terminal completion",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project",{enabled:true});const wake=await f.watch.tick("agent","project");assert.equal((await f.store.read()).agents["agent:project"].cursor,0);await f.watch.complete("agent","project",{run_id:wake.run_id});const state=await f.store.read();assert.equal(state.agents["agent:project"].cursor,1);assert.equal(state.agents["agent:project"].completions[0].event_id,"event-1");}finally{await cleanup(f);}});
test("cursor and completion survive store restart and reconfiguration",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project",{enabled:true});const wake=await f.watch.tick("agent","project");await f.watch.complete("agent","project",{run_id:wake.run_id});const reopened=new FileWatchStore(f.store.file);assert.equal((await reopened.read()).agents["agent:project"].cursor,1);const restarted=new PortWatch({store:reopened,inbox:authorizedInboxSource(async()=>[]),runner:new RecordingRunner()});await restarted.configure("agent","project",{enabled:true,scopes:["events:write"]});assert.equal((await reopened.read()).agents["agent:project"].cursor,1);}finally{await cleanup(f);}});
test("crash before atomic completion re-delivers event id after lease expiry",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project",{enabled:true});const first=await f.watch.tick("agent","project");assert.equal((await f.watch.tick("agent","project")).reason,"wip_limit");await f.watch.expireLease("agent","project",first.lease_token);const second=await f.watch.tick("agent","project");assert.equal(second.action,"wake");assert.deepEqual(f.runner.invocations.map(x=>x.context.event_ids[0]),["event-1","event-1"]);}finally{await cleanup(f);}});
test("ordinary cursor rewind is refused; operator rewind is audited",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project",{enabled:true});const wake=await f.watch.tick("agent","project");await f.watch.complete("agent","project",{run_id:wake.run_id});await assert.rejects(()=>f.watch.rewind("agent","project",0),/CURSOR_REWIND_REFUSED/);await f.watch.rewind("agent","project",0,{operator:true});const state=await f.store.read();assert.equal(state.agents["agent:project"].cursor,0);assert.equal(state.events.at(-1).kind,"cursor.rewound");}finally{await cleanup(f);}});
test("off by default blocks wake; enable is positive control",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project");assert.equal((await f.watch.tick("agent","project")).reason,"disabled");assert.equal(f.runner.invocations.length,0);await f.watch.control("agent","project","enable");assert.equal((await f.watch.tick("agent","project")).action,"wake");}finally{await cleanup(f);}});
test("pause blocks new wake while active run remains",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project",{enabled:true});const wake=await f.watch.tick("agent","project");await f.watch.control("agent","project","pause");assert.equal((await f.watch.tick("agent","project")).reason,"paused");assert.equal((await f.store.read()).agents["agent:project"].active_run.run_id,wake.run_id);await f.watch.complete("agent","project",{run_id:wake.run_id});assert.equal((await f.store.read()).agents["agent:project"].cursor,1);}finally{await cleanup(f);}});
test("stop blocks wakes and revokes active lease",async()=>{const f=await fixture([handoff()]);try{await f.watch.configure("agent","project",{enabled:true});const wake=await f.watch.tick("agent","project");await f.watch.control("agent","project","stop");assert.equal((await f.watch.tick("agent","project")).reason,"stopped");const active=(await f.store.read()).agents["agent:project"].active_run;assert.equal(active.termination_requested,true);assert.equal(active.lease_status,"revoked");await assert.rejects(()=>f.watch.complete("agent","project",{run_id:wake.run_id}),/LEASE_NOT_ACTIVE/);}finally{await cleanup(f);}});
test("WIP one prevents a second wake",async()=>{const f=await fixture([handoff(1),handoff(2)]);try{await f.watch.configure("agent","project",{enabled:true});assert.equal((await f.watch.tick("agent","project")).action,"wake");assert.equal((await f.watch.tick("agent","project")).reason,"wip_limit");assert.equal(f.runner.invocations.length,1);}finally{await cleanup(f);}});
test("concurrent ticks reserve one WIP slot before runner invocation",async()=>{const f=await fixture([handoff(1)]);try{await f.watch.configure("agent","project",{enabled:true});const decisions=await Promise.all([f.watch.tick("agent","project"),f.watch.tick("agent","project")]);assert.deepEqual(decisions.map(d=>d.action).sort(),["skip","wake"]);assert.equal(decisions.find(d=>d.action==="skip").reason,"wip_limit");assert.equal(f.runner.invocations.length,1);}finally{await cleanup(f);}});
test("decision function is deterministic",()=>{const input={watch:{enabled:true,status:"enabled",active_run:null},cursor:0,events:[handoff()]};assert.deepEqual(decideWatch(input),decideWatch(structuredClone(input)));});
test("cadence defaults to 240 and bounded jitter never skips tick",()=>{assert.equal(nextPollDelay(),240);assert.equal(nextPollDelay({sample:0}),216);assert.equal(nextPollDelay({sample:1}),264);assert.equal(nextPollDelay({cadence_seconds:60,jitter_fraction:0.2,sample:0.5}),60);assert.ok(nextPollDelay({cadence_seconds:1,jitter_fraction:0.99,sample:0})>0);});
test("unbranded broad inbox source is structurally refused",async()=>{const f=await fixture();try{assert.throws(()=>new PortWatch({store:f.store,inbox:{queryAuthorized:async()=>[]},runner:f.runner}),/already-authorized inbox source/);}finally{await cleanup(f);}});
