import assert from "node:assert/strict";
import test from "node:test";
import { compileSetup } from "../packages/git-adapter/src/workspace-setup.mjs";
const sessionManagerModule=process.env.SETUP_SESSION_MANAGER_MODULE
  ? await import(process.env.SETUP_SESSION_MANAGER_MODULE)
  : await import("../packages/git-adapter/src/workspace-session.mjs");
const { SetupSessionManager, founderAuthenticator, founderAuthorityResolver }=sessionManagerModule;

const plan=()=>compileSetup({schema_version:0,created_at:"2026-08-14T12:00:00Z",founder:{principal_id:"founder",scopes:["events:write"],assignable_trust:["untrusted_agent"],expires_at:null},repository:{provider:"github",owner:"acme",name:"engram",default_branch:"main",permissions:["contents:read"],depends_on:[]},database:{mode:"connect_existing",target:"postgresql",depends_on:[]},participants:[],groups:[],import:{paths:[],include_history:false,depends_on:[]},welcome:{expiry_days:14,depends_on:[]}});
function fixture(now="2026-08-14T12:00:00Z"){let current=new Date(now),sequence=0;const manager=new SetupSessionManager({authenticator:founderAuthenticator(async credential=>{assert.equal(credential,"fixture-only-founder-credential");return {principal_id:"founder"};}),authorityResolver:founderAuthorityResolver(async principal_id=>({principal_id,scopes:["setup:plan:execute","setup:repository"],expires_at:"2026-08-20T00:00:00Z"})),clock:()=>new Date(current),idFactory:kind=>`${kind}-${++sequence}`});return {manager,setTime:value=>current=new Date(value)};}
const start=(manager,overrides={})=>manager.start({credential:"fixture-only-founder-credential",scopes:["setup:plan:execute"],expires_at:"2026-08-15T00:00:00Z",...overrides});
const approve=async(manager,session_id)=>{const compiled=plan();return {compiled,approval:await manager.approvePlan(session_id,compiled)};};

test("session binds authenticated founder with narrowed scopes and absolute expiry",async()=>{const {manager}=fixture(),session=await start(manager);assert.deepEqual(session,{session_id:"session-1",status:"active",founder_principal_id:"founder",scopes:["setup:plan:execute"],expires_at:"2026-08-15T00:00:00Z"});assert.deepEqual(await manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:1,delegations:1,credentials:0});});
test("approved step executes only within its live session",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);assert.equal((await manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect")).status,"authorized");});
test("completion structurally removes identity, delegation, approval, and credential",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);assert.deepEqual(await manager.complete(session.session_id),{session_id:"session-1",status:"completed",authority:false});assert.deepEqual(await manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:0,delegations:0,credentials:0});assert.deepEqual(await manager.state(session.session_id),{session_id:"session-1",status:"completed",authority:false});assert.equal(JSON.stringify(await manager.state(session.session_id)).includes("founder"),false);await assert.rejects(()=>manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_REPLAY_REFUSED");});
test("expired session refuses approved execution and leaves no identity",async()=>{const f=fixture(),session=await start(f.manager),{compiled,approval}=await approve(f.manager,session.session_id);f.setTime("2026-08-15T00:00:00Z");assert.deepEqual(await f.manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:0,delegations:0,credentials:0});assert.deepEqual(await f.manager.state(session.session_id),{session_id:"session-1",status:"expired",authority:false});await assert.rejects(()=>f.manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="SESSION_EXPIRED");});
test("untouched expired delegation is swept while an untouched live session remains counted",async()=>{const f=fixture(),expired=await start(f.manager),live=await start(f.manager,{expires_at:"2026-08-16T00:00:00Z"});f.setTime("2026-08-15T00:00:00Z");assert.deepEqual(await f.manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:1,delegations:1,credentials:0});assert.deepEqual(await f.manager.state(expired.session_id),{session_id:expired.session_id,status:"expired",authority:false});assert.equal((await f.manager.state(live.session_id)).status,"active");assert.deepEqual((await f.manager.state(live.session_id)).scopes,["setup:plan:execute"]);});
test("torn-down session cannot authorize and replayed approval is refused",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);await manager.complete(session.session_id);await assert.rejects(()=>manager.authorize(session.session_id),error=>error.code==="SESSION_REVOKED");await assert.rejects(()=>manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_REPLAY_REFUSED");});
test("approval from session A cannot execute under session B",async()=>{const {manager}=fixture(),a=await start(manager),b=await start(manager),{compiled,approval}=await approve(manager,a.session_id);await assert.rejects(()=>manager.executeApprovedStep(b.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_SESSION_MISMATCH");assert.equal((await manager.executeApprovedStep(a.session_id,approval,compiled,"repository.connect")).status,"authorized");});
test("scope and expiry ceilings reuse W0 predicates",async()=>{const {manager}=fixture();await assert.rejects(()=>start(manager,{scopes:["setup:admin"]}),error=>error.code==="SESSION_SCOPE_EXCEEDS_FOUNDER");await assert.rejects(()=>start(manager,{expires_at:"2026-08-21T00:00:00Z"}),error=>error.code==="SESSION_OUTLIVES_FOUNDER");assert.equal((await start(manager,{scopes:["setup:repository"],expires_at:"2026-08-20T00:00:00Z"})).status,"active");});
test("non-setup scope and unbounded session are refused",async()=>{const {manager}=fixture();await assert.rejects(()=>start(manager,{scopes:["events:write"]}),error=>error.code==="SESSION_SCOPE_NOT_SETUP");await assert.rejects(()=>start(manager,{expires_at:null}),error=>error.code==="SESSION_ABSOLUTE_EXPIRY_REQUIRED");assert.equal((await start(manager)).status,"active");});
test("abandonment leaves no partial authority",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);await manager.abandon(session.session_id);assert.deepEqual(await manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:0,delegations:0,credentials:0});assert.equal((await manager.state(session.session_id)).status,"abandoned");await assert.rejects(()=>manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_REPLAY_REFUSED");});
test("state machine is deterministic under injected clock and ids",async()=>{async function run(){const f=fixture(),session=await start(f.manager),{compiled,approval}=await approve(f.manager,session.session_id),authorized=await f.manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),ended=await f.manager.complete(session.session_id);return {session,approval,authorized,ended,inventory:await f.manager.identityInventory()};}assert.deepEqual(await run(),await run());});
test("authenticator returns identity only and fixture credential is never stored",async()=>{const {manager}=fixture(),session=await start(manager);assert.equal(JSON.stringify(await manager.state(session.session_id)).includes("fixture-only-founder-credential"),false);assert.equal((await manager.identityInventory()).credentials,0);});
