import assert from "node:assert/strict";
import { createHmac, generateKeyPairSync, sign } from "node:crypto";
import test from "node:test";

const verifierModule=process.env.W1_1_OIDC_VERIFIER_MODULE
  ? await import(process.env.W1_1_OIDC_VERIFIER_MODULE)
  : await import("../packages/git-adapter/src/oidc-verifier.mjs");
const {createOidcVerifier}=verifierModule,selectedCase=process.env.W1_1_OIDC_CASE??null;
const ISSUER="https://synthetic-idp.invalid",AUDIENCE="engramport-setup",NONCE="synthetic-nonce",NOW=Date.parse("2026-08-25T01:00:00Z");

function keyFixture(kid,status){
  const {privateKey,publicKey}=generateKeyPairSync("rsa",{modulusLength:2048});
  return {privateKey,publicPem:publicKey.export({type:"spki",format:"pem"}),jwk:{...publicKey.export({format:"jwk"}),kid,alg:"RS256",use:"sig",status}};
}
const current=keyFixture("current","active"),retired=keyFixture("retired","retired"),jwks={keys:[current.jwk,retired.jwk]};
const claims=overrides=>({iss:ISSUER,sub:"synthetic-founder-subject",aud:AUDIENCE,exp:Math.floor((NOW+15*60_000)/1000),nonce:NONCE,principal_id:"caller-asserted-principal",...overrides});
const encode=value=>Buffer.from(typeof value==="string"?value:JSON.stringify(value)).toString("base64url");
function rs256Token(payload=claims({}),key=current,header={alg:"RS256",kid:key.jwk.kid,typ:"JWT"}){const head=encode(header),body=encode(payload),input=`${head}.${body}`;return `${input}.${sign("RSA-SHA256",Buffer.from(input),key.privateKey).toString("base64url")}`;}
function noneToken(payload=claims({})){return `${encode({alg:"none",kid:current.jwk.kid,typ:"JWT"})}.${encode(payload)}.${encode("unsigned")}`;}
function hs256Token(payload=claims({})){const head=encode({alg:"HS256",kid:current.jwk.kid,typ:"JWT"}),body=encode(payload),input=`${head}.${body}`;return `${input}.${createHmac("sha256",current.publicPem).update(input).digest("base64url")}`;}
const makeVerifier=()=>createOidcVerifier({jwks,issuer:ISSUER,audience:AUDIENCE,clock:()=>new Date(NOW)});
async function result(operation){try{return {outcome:"accepted",value:await operation()};}catch(error){return {outcome:error.code,error};}}
function check(name,fn){test(name,{skip:selectedCase!==null&&selectedCase!==name},fn);}

check("signature",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),token=rs256Token(),parts=token.split("."),tampered=`${parts[0]}.${parts[1]}.${encode("not-the-signature")}`,negative=await result(()=>verifier.verify({token:tampered,nonce:NONCE}));console.log(`W1_1_OIDC signature positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_SIGNATURE_REFUSED");});
check("rotation",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),negative=await result(()=>verifier.verify({token:rs256Token(claims({}),retired),nonce:NONCE}));console.log(`W1_1_OIDC rotation positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_KEY_RETIRED");});
check("alg-none",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),negative=await result(()=>verifier.verify({token:noneToken(),nonce:NONCE}));console.log(`W1_1_OIDC alg-none positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_ALGORITHM_NONE_REFUSED");});
check("alg-hs256",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),negative=await result(()=>verifier.verify({token:hs256Token(),nonce:NONCE}));console.log(`W1_1_OIDC alg-hs256 positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_ALGORITHM_CONFUSION_REFUSED");});
check("issuer",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),negative=await result(()=>verifier.verify({token:rs256Token(claims({iss:"https://foreign-idp.invalid"})),nonce:NONCE}));console.log(`W1_1_OIDC issuer positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_ISSUER_REFUSED");});
check("audience",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),negative=await result(()=>verifier.verify({token:rs256Token(claims({aud:"foreign-client"})),nonce:NONCE}));console.log(`W1_1_OIDC audience positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_AUDIENCE_REFUSED");});
check("expiry",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),negative=await result(()=>verifier.verify({token:rs256Token(claims({exp:Math.floor((NOW-1)/1000)})),nonce:NONCE}));console.log(`W1_1_OIDC expiry positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_EXPIRED");});
check("nonce",async()=>{const verifier=makeVerifier(),positive=await result(()=>verifier.verify({token:rs256Token(),nonce:NONCE})),negative=await result(()=>verifier.verify({token:rs256Token(),nonce:"different-nonce"}));console.log(`W1_1_OIDC nonce positive=${positive.outcome} negative=${negative.outcome}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_NONCE_REFUSED");});
check("claims-surface",async()=>{const verifier=makeVerifier(),verified=await verifier.verify({token:rs256Token(),nonce:NONCE}),surface=Object.keys(verified).sort().join(","),negative=Object.hasOwn(verified,"principal_id")?"principal_id":"absent";console.log(`W1_1_OIDC claims-surface positive=${surface} negative=${negative}`);assert.deepEqual(verified,{iss:ISSUER,sub:"synthetic-founder-subject",aud:AUDIENCE,exp:Math.floor((NOW+15*60_000)/1000),nonce:NONCE});assert.equal(negative,"absent");assert.equal(Object.hasOwn(verified,"token"),false);});
check("retention",async()=>{const verifier=makeVerifier(),positiveToken=rs256Token(),positive=await result(()=>verifier.verify({token:positiveToken,nonce:NONCE})),afterPositive=verifier.transientInventory(),negativeToken=rs256Token(claims({iss:"https://foreign-idp.invalid"})),negative=await result(()=>verifier.verify({token:negativeToken,nonce:NONCE})),afterNegative=verifier.transientInventory(),positiveState=afterPositive.tokens===0&&afterPositive.claims===0?"cleared":"retained",negativeState=afterNegative.tokens===0&&afterNegative.claims===0?"cleared":"retained";console.log(`W1_1_OIDC retention positive=${positiveState} negative=${negativeState}`);assert.equal(positive.outcome,"accepted");assert.equal(negative.outcome,"OIDC_ISSUER_REFUSED");assert.deepEqual(afterPositive,{tokens:0,claims:0});assert.deepEqual(afterNegative,{tokens:0,claims:0});});
