import assert from "node:assert/strict";
import childProcess from "node:child_process";
import fsPromises from "node:fs/promises";
import http from "node:http";
import https from "node:https";
import net from "node:net";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { compileSetup } from "../packages/git-adapter/src/workspace-setup.mjs";
import { dryRunSetup, executeDryRun } from "../packages/git-adapter/src/workspace-dry-run.mjs";

function setup(){return {schema_version:0,created_at:"2026-08-14T12:00:00Z",founder:{principal_id:"founder",scopes:["events:write","repo:read"],assignable_trust:["untrusted_agent"],expires_at:null},repository:{provider:"github",owner:"acme",name:"engram",default_branch:"main",permissions:["contents:read","pull_requests:write_non_default","webhooks:receive"],depends_on:[]},database:{mode:"provision_managed",target:"postgresql-pgvector",depends_on:["repository.connect"]},participants:[{id:"agent",kind:"agent",role:"contributor",scopes:["events:write"],capabilities:["implementation"],groups:[],trust:"untrusted_agent",projects:["project-1"],expires_at:null,owner_id:"owner",depends_on:["participant.owner"]},{id:"owner",kind:"human",role:"owner",scopes:["events:write"],capabilities:[],groups:[],trust:"untrusted_agent",projects:["project-1"],expires_at:null,owner_id:null,depends_on:[]}],groups:[],import:{paths:["docs/","src/"],include_history:true,depends_on:["repository.connect"]},welcome:{expiry_days:14,depends_on:["participant.agent"]}};}
async function temporary(){return mkdtemp(path.join(os.tmpdir(),"wizard-dry-run-"));}

test("valid plan transcript exactly covers compiled sequence and digests",async()=>{const dir=await temporary();try{const compiled=compileSetup(setup()),transcript=executeDryRun(compiled,{temporary_directory:dir});assert.deepEqual(transcript.sequence,compiled.map(s=>s.step_id));assert.deepEqual(transcript.steps.map(s=>s.step_id),compiled.map(s=>s.step_id));assert.equal(transcript.steps.length,compiled.length);for(const [index,entry] of transcript.steps.entries()){assert.equal(entry.kind,compiled[index].kind);assert.equal(entry.consequential,compiled[index].consequential);assert.deepEqual(entry.effect.operation.length>0,true);if(entry.consequential)assert.equal(entry.action_digest,compiled[index].action_digest);else assert.equal("action_digest" in entry,false);}}finally{await rm(dir,{recursive:true,force:true});}});
test("dry-run output is deterministic",async()=>{const dir=await temporary();try{assert.deepEqual(dryRunSetup(setup(),{temporary_directory:dir}),dryRunSetup(setup(),{temporary_directory:dir}));}finally{await rm(dir,{recursive:true,force:true});}});
test("headline: provisioning, pull-request, and import effects cause zero side effects",async()=>{const dir=await temporary(),counts={writes:0,connections:0,subprocesses:0,database:0};const restorations=[];const trap=(object,name,counter,{database=false}={})=>{const original=object[name];object[name]=(...args)=>{counts[counter]++;if(database)counts.database++;throw new Error(`PROHIBITED_${counter.toUpperCase()}:${name}:${args.length}`);};restorations.push(()=>object[name]=original);};
  for(const name of ["writeFile","appendFile","rename","mkdir","open","rm","cp"])trap(fsPromises,name,"writes");for(const name of ["connect","createConnection"])trap(net,name,"connections",{database:true});for(const [object,names] of [[http,["request","get"]],[https,["request","get"]]])for(const name of names)trap(object,name,"connections");for(const name of ["spawn","spawnSync","exec","execSync","execFile","execFileSync","fork"])trap(childProcess,name,"subprocesses",{database:true});const priorFetch=globalThis.fetch;globalThis.fetch=(...args)=>{counts.connections++;throw new Error(`PROHIBITED_CONNECTIONS:fetch:${args.length}`);};
  try{const transcript=dryRunSetup(setup(),{temporary_directory:dir});assert.ok(transcript.steps.some(s=>s.effect.operation==="configure_database"));assert.ok(transcript.steps.some(s=>s.effect.operation==="connect_repository"));assert.ok(transcript.steps.some(s=>s.effect.operation==="import_history"));assert.deepEqual(counts,{writes:0,connections:0,subprocesses:0,database:0});}finally{globalThis.fetch=priorFetch;for(const restore of restorations.reverse())restore();await rm(dir,{recursive:true,force:true});}});
test("compiler-refused plan produces no transcript",async()=>{const dir=await temporary();try{const invalid=setup();invalid.repository.permissions.push("contents:write");let transcript;assert.throws(()=>{transcript=dryRunSetup(invalid,{temporary_directory:dir});},error=>error.code==="GITHUB_PERMISSION_REFUSED");assert.equal(transcript,undefined);const valid=dryRunSetup(setup(),{temporary_directory:dir});assert.ok(valid.steps.length);}finally{await rm(dir,{recursive:true,force:true});}});
test("hand-built or cloned step list cannot bypass compiler",async()=>{const dir=await temporary();try{assert.throws(()=>executeDryRun([],{temporary_directory:dir}),error=>error.code==="UNCOMPILED_PLAN_REFUSED");const cloned=structuredClone(compileSetup(setup()));assert.throws(()=>executeDryRun(cloned,{temporary_directory:dir}),error=>error.code==="UNCOMPILED_PLAN_REFUSED");assert.ok(executeDryRun(compileSetup(setup()),{temporary_directory:dir}).steps.length);}finally{await rm(dir,{recursive:true,force:true});}});
test("temporary directory is required",()=>{assert.throws(()=>executeDryRun(compileSetup(setup())),error=>error.code==="TEMP_DIRECTORY_REQUIRED");});
