import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import test from "node:test";
import { diffSetupPlans } from "../packages/git-adapter/src/workspace-approval.mjs";
import { SetupSessionManager, founderAuthenticator } from "../packages/git-adapter/src/workspace-session.mjs";
import { ACTION_DIGEST_EXCLUSIONS, ACTION_PROFILE, PLAN_PROFILE, actionDigest, compileSetup, computePlanDigest, loadSetupPlan, serializeSetupPlan } from "../packages/git-adapter/src/workspace-setup.mjs";
import { canonicalJson } from "../packages/git-adapter/src/welcome-verify.mjs";

function setup(){return {schema_version:0,created_at:"2026-08-14T12:00:00Z",founder:{principal_id:"founder",scopes:["events:write"],assignable_trust:["untrusted_agent"],expires_at:null},repository:{provider:"github",owner:"acme",name:"engram",default_branch:"main",permissions:["contents:read"],depends_on:[]},database:{mode:"connect_existing",target:"postgresql",depends_on:["repository.connect"]},participants:[{id:"agent",kind:"agent",role:"contributor",scopes:["events:write"],capabilities:["fixture-only"],groups:[],trust:"untrusted_agent",projects:["project"],expires_at:null,owner_id:"founder-record",depends_on:[]}],groups:[],import:{paths:["docs/"],include_history:false,depends_on:["repository.connect"]},welcome:{expiry_days:14,depends_on:["participant.agent"]}};}
function validSetup(){const value=setup();value.participants[0].kind="human";value.participants[0].owner_id=null;return value;}
function managerFixture(){let sequence=0;return new SetupSessionManager({authenticator:founderAuthenticator(async credential=>{assert.equal(credential,"fixture-only-founder-credential");return {principal_id:"founder"};}),clock:()=>new Date("2026-08-14T12:00:00Z"),idFactory:kind=>`${kind}-${++sequence}`});}
async function approved(){const manager=managerFixture(),session=await manager.start({credential:"fixture-only-founder-credential",founder_authority:{principal_id:"founder",scopes:["setup:plan:execute"],expires_at:"2026-08-20T00:00:00Z"},scopes:["setup:plan:execute"],expires_at:"2026-08-15T00:00:00Z"}),plan=compileSetup(validSetup()),approval=manager.approvePlan(session.session_id,plan);assert.equal(plan.length,5);return {manager,session,plan,approval};}
function envelope(plan){return JSON.parse(serializeSetupPlan(plan));}
function selfConsistent(plan,mutate){const value=envelope(plan);mutate(value.steps);for(const step of value.steps)step.action_digest=actionDigest(step);value.plan_digest=computePlanDigest(value.steps);return loadSetupPlan(value);}
const hash=value=>createHash("sha256").update(canonicalJson(value)).digest("hex");
function v2Envelope(plan){const value=envelope(plan);value.action_profile="engramport-action-v2";for(const step of value.steps)step.action_digest=hash({step_id:step.step_id,kind:step.kind,parameters:step.parameters});value.plan_digest=hash({profile:PLAN_PROFILE,action_profile:value.action_profile,steps:value.steps.map(({step_id,kind,action_digest})=>({step_id,kind,action_digest}))});return value;}
const executeAll=({manager,session,plan,approval},presented=plan)=>presented.map(step=>manager.executeApprovedStep(session.session_id,approval,presented,step.step_id));
async function refusal(name,code,mutate){await test(name,async()=>{const fixture=await approved();assert.equal(executeAll(fixture).length,5);const changed=selfConsistent(fixture.plan,mutate);assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,changed,changed[0].step_id),error=>error.code===code);});}

test("digests and portable plan identity survive serialization and another process",()=>{const plan=compileSetup(validSetup()),loaded=loadSetupPlan(serializeSetupPlan(plan));assert.equal(ACTION_PROFILE,"engramport-action-v3");assert.equal(PLAN_PROFILE,"engramport-plan-v1");assert.equal(loaded.plan_digest,plan.plan_digest);assert.deepEqual(loaded,plan);const moduleUrl=new URL("../packages/git-adapter/src/workspace-setup.mjs",import.meta.url).href,source=`import {compileSetup} from ${JSON.stringify(moduleUrl)};console.log(compileSetup(${JSON.stringify(validSetup())}).plan_digest);`,child=spawnSync(process.execPath,["--input-type=module","--eval",source],{encoding:"utf8"});assert.equal(child.status,0,child.stderr);assert.equal(child.stdout.trim(),plan.plan_digest);});
test("compiled serialized reloaded plan executes under its genuine grouped approval",async()=>{const fixture=await approved(),loaded=loadSetupPlan(serializeSetupPlan(fixture.plan)),approval=structuredClone(fixture.approval);assert.equal(executeAll({...fixture,approval},loaded).length,5);assert.deepEqual(approval.steps,fixture.plan.map(({step_id,action_digest})=>({step_id,action_digest})));assert.equal(approval.plan_digest,loaded.plan_digest);});
test("grouped approval authorizes all five steps in approved order",async()=>{const fixture=await approved(),results=executeAll(fixture);assert.deepEqual(results.map(result=>result.index),[0,1,2,3,4]);assert.deepEqual(results.map(result=>result.step_id),fixture.plan.map(step=>step.step_id));});
test("diffing a plan against itself is empty",async()=>{const {plan}=await approved();assert.deepEqual(diffSetupPlans(plan,plan),{added:[],removed:[],reordered:[],substituted:[],modified:[]});});
test("source dependency order is normalized only during compilation",()=>{const a=validSetup(),b=validSetup();a.welcome.depends_on=["repository.connect","participant.agent"];b.welcome.depends_on=["participant.agent","repository.connect"];const first=compileSetup(a),second=compileSetup(b),welcome=first.find(step=>step.step_id==="welcome.defaults");assert.deepEqual(welcome.depends_on,["participant.agent","repository.connect"]);assert.equal(first.plan_digest,second.plan_digest);assert.deepEqual(first,second);});

await refusal("reordered steps are refused with paired genuine-plan control","PLAN_STEPS_REORDERED",steps=>{[steps[0],steps[1]]=[steps[1],steps[0]];});
await refusal("inserted step is refused with paired genuine-plan control","PLAN_STEP_INSERTED",steps=>{const parameters={fixture:true};steps.splice(1,0,{step_id:"fixture.inserted",kind:"fixture.inserted",parameters,consequential:true,depends_on:[],action_digest:actionDigest({step_id:"fixture.inserted",kind:"fixture.inserted",parameters})});});
await refusal("removed step is refused with paired genuine-plan control","PLAN_STEP_REMOVED",steps=>{steps.splice(1,1);});
await refusal("substituted step is refused with paired genuine-plan control","PLAN_STEP_SUBSTITUTED",steps=>{steps[1]={...steps[1],step_id:"fixture.substitute",kind:"fixture.substitute"};});
await refusal("modified parameters are refused with paired genuine-plan control","PLAN_STEP_MODIFIED",steps=>{steps.find(step=>step.step_id==="repository.connect").parameters.owner="mallory";});
test("forged but self-consistent plan is not authorized by a genuine approval",async()=>{const fixture=await approved();assert.equal(executeAll(fixture).length,5);const forged=selfConsistent(fixture.plan,steps=>{steps.find(step=>step.step_id==="repository.connect").parameters.owner="forger";});assert.notEqual(forged.plan_digest,fixture.approval.plan_digest);assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,forged,forged[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");});
test("one consequential flag change is self-consistent but refused by genuine approval",async()=>{const fixture=await approved(),changed=selfConsistent(fixture.plan,steps=>{steps[0].consequential=!steps[0].consequential;});assert.equal(changed[0].consequential,!fixture.plan[0].consequential);assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,changed,changed[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");assert.equal(executeAll(fixture).length,5);});
test("all consequential flags changed is the refused F8 control",async()=>{const fixture=await approved(),changed=selfConsistent(fixture.plan,steps=>{for(const step of steps)step.consequential=!step.consequential;});assert.notEqual(changed.plan_digest,fixture.plan.plan_digest);assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,changed,changed[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");assert.equal(executeAll(fixture).length,5);});
test("added dependency is self-consistent but refused by genuine approval",async()=>{const fixture=await approved(),changed=selfConsistent(fixture.plan,steps=>{steps.find(step=>step.step_id==="welcome.defaults").depends_on.push("repository.connect");});assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,changed,changed[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");assert.equal(executeAll(fixture).length,5);});
test("removed dependency is self-consistent but refused by genuine approval",async()=>{const fixture=await approved(),changed=selfConsistent(fixture.plan,steps=>{steps.find(step=>step.step_id==="welcome.defaults").depends_on=[];});assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,changed,changed[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");assert.equal(executeAll(fixture).length,5);});
test("wire dependency order is verified verbatim and never normalized",async()=>{const fixture=await approved(),withTwo=selfConsistent(fixture.plan,steps=>{steps.find(step=>step.step_id==="welcome.defaults").depends_on=["participant.agent","repository.connect"];});const approvedTwo=fixture.manager.approvePlan(fixture.session.session_id,withTwo),wireReordered=selfConsistent(withTwo,steps=>{steps.find(step=>step.step_id==="welcome.defaults").depends_on.reverse();}),welcome=wireReordered.find(step=>step.step_id==="welcome.defaults");assert.deepEqual(welcome.depends_on,["repository.connect","participant.agent"]);assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,approvedTwo,wireReordered,wireReordered[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");assert.equal(fixture.manager.executeApprovedStep(fixture.session.session_id,approvedTwo,withTwo,withTwo[0].step_id).status,"authorized");});
test("cross-plan approval is refused with paired approved-plan control",async()=>{const fixture=await approved();assert.equal(executeAll(fixture).length,5);const other=selfConsistent(fixture.plan,steps=>{steps.at(-1).parameters.expiry_days=30;});assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,other,other[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");});
test("action v3 digest preserves step id and kind coverage",()=>{const parameters={same:true},a=actionDigest({step_id:"a",kind:"same",parameters}),b=actionDigest({step_id:"b",kind:"same",parameters}),c=actionDigest({step_id:"a",kind:"different",parameters});assert.notEqual(a,b);assert.notEqual(a,c);assert.equal(a,actionDigest({step_id:"a",kind:"same",parameters}));});
test("action v3 coverage is deny-by-default with only its self digest excluded",()=>{assert.deepEqual(Object.keys(ACTION_DIGEST_EXCLUSIONS),["action_digest"]);const base={step_id:"a",kind:"same",parameters:{same:true},consequential:true,depends_on:[]},future={...base,future_review_field:"covered"},prototypeNamed={...base,toString:"also covered"};assert.notEqual(actionDigest(base),actionDigest(future));assert.notEqual(actionDigest(base),actionDigest(prototypeNamed));assert.equal(actionDigest({...base,action_digest:"ignored"}),actionDigest(base));});
test("a future wire field is preserved, covered, diffed, and refused without an exclusion",async()=>{const fixture=await approved(),changed=selfConsistent(fixture.plan,steps=>{steps[0].future_review_field="covered";});assert.equal(changed[0].future_review_field,"covered");assert.deepEqual(diffSetupPlans(fixture.plan,changed).modified[0].fields,[{field:"future_review_field",before:undefined,after:"covered"}]);assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,changed,changed[0].step_id),error=>error.code==="PLAN_STEP_MODIFIED");assert.equal(executeAll(fixture).length,5);});
test("v2 wire is refused with a specific profile error and differs from v3 plan identity",()=>{const plan=compileSetup(validSetup()),wire=v2Envelope(plan);assert.notEqual(wire.plan_digest,plan.plan_digest);assert.throws(()=>loadSetupPlan(wire),error=>error.code==="ACTION_PROFILE_UNSUPPORTED"&&error.message.includes("engramport-action-v2"));assert.equal(loadSetupPlan(serializeSetupPlan(plan)).plan_digest,plan.plan_digest);});
test("tampered serialized plan is refused on load with paired round trip",()=>{const plan=compileSetup(validSetup());assert.equal(loadSetupPlan(serializeSetupPlan(plan)).plan_digest,plan.plan_digest);const tampered=envelope(plan);tampered.steps[0].parameters.owner="mallory";assert.throws(()=>loadSetupPlan(tampered),error=>error.code==="ACTION_DIGEST_MISMATCH");});
test("verified plan parameters are deeply immutable",()=>{const plan=compileSetup(validSetup()),participant=plan.find(step=>step.step_id==="participant.agent");assert.throws(()=>participant.parameters.capabilities.push("forged"),TypeError);assert.deepEqual(participant.parameters.capabilities,["fixture-only"]);assert.equal(loadSetupPlan(serializeSetupPlan(plan)).plan_digest,plan.plan_digest);});
test("hand-built step list is refused at approval and execution",async()=>{const fixture=await approved(),raw=structuredClone(fixture.plan);assert.throws(()=>fixture.manager.approvePlan(fixture.session.session_id,raw),error=>error.code==="UNCOMPILED_PLAN_REFUSED");assert.throws(()=>fixture.manager.executeApprovedStep(fixture.session.session_id,fixture.approval,raw,raw[0].step_id),error=>error.code==="UNCOMPILED_PLAN_REFUSED");assert.equal(executeAll(fixture).length,5);});
test("structured diff reports all classes, covered fields, and parameter paths",async()=>{const {plan}=await approved();const reordered=selfConsistent(plan,steps=>{[steps[0],steps[1]]=[steps[1],steps[0]];}),inserted=selfConsistent(plan,steps=>{steps.splice(1,0,{...steps[0],step_id:"fixture.added"});}),removed=selfConsistent(plan,steps=>{steps.splice(1,1);}),substituted=selfConsistent(plan,steps=>{steps[1]={...steps[1],step_id:"fixture.substituted"};}),modified=selfConsistent(plan,steps=>{steps.find(step=>step.step_id==="repository.connect").parameters.owner="mallory";}),consequential=selfConsistent(plan,steps=>{steps[0].consequential=!steps[0].consequential;}),dependencies=selfConsistent(plan,steps=>{steps.find(step=>step.step_id==="welcome.defaults").depends_on.push("repository.connect");});assert.ok(diffSetupPlans(plan,reordered).reordered.some(item=>item.step_id===plan[0].step_id));assert.deepEqual(diffSetupPlans(plan,inserted).added[0].step_id,"fixture.added");assert.deepEqual(diffSetupPlans(plan,removed).removed[0].step_id,plan[1].step_id);assert.deepEqual(diffSetupPlans(plan,substituted).substituted[0].approved_step_id,plan[1].step_id);assert.deepEqual(diffSetupPlans(plan,modified).modified.find(item=>item.step_id==="repository.connect").parameters,[{path:"owner",before:"acme",after:"mallory"}]);assert.deepEqual(diffSetupPlans(plan,consequential).modified[0].fields,[{field:"consequential",before:plan[0].consequential,after:!plan[0].consequential}]);assert.deepEqual(diffSetupPlans(plan,dependencies).modified.find(item=>item.step_id==="welcome.defaults").fields,[{field:"depends_on",before:["participant.agent"],after:["participant.agent","repository.connect"]}]);});
