import assert from "node:assert/strict";
import test from "node:test";
import { compileSetup } from "../packages/git-adapter/src/workspace-setup.mjs";
const sessionManagerModule=process.env.SETUP_SESSION_MANAGER_MODULE
  ? await import(process.env.SETUP_SESSION_MANAGER_MODULE)
  : await import("../packages/git-adapter/src/workspace-session.mjs");
const { SetupSessionManager, founderAuthenticator, founderAuthorityResolver }=sessionManagerModule;
const postgresMode=process.env.SETUP_SESSION_TEST_ADAPTER==="postgres";
const principal=postgresMode?"11000000-0000-0000-0000-000000000001":"founder";
const baseTime=postgresMode?Date.now():Date.parse("2026-08-14T12:00:00Z");
const atHours=hours=>new Date(baseTime+hours*60*60*1000).toISOString();
const defaultExpiry=atHours(12),liveExpiry=atHours(18),founderExpiry=atHours(48),outlivingExpiry=atHours(49),positiveCeilingExpiry=postgresMode?atHours(20):founderExpiry;
let maintenancePool,adminPool,PostgresSetupSessionStore;
if(postgresMode){
  const {Pool}=await import("pg");
  ({PostgresSetupSessionStore}=await import("../packages/git-adapter/src/workspace-session-store.mjs"));
  maintenancePool=new Pool({connectionString:process.env.W1_1_MANAGER_DATABASE_URL,max:4,connectionTimeoutMillis:1000,statement_timeout:5000});
  adminPool=new Pool({connectionString:process.env.W1_1_MANAGER_POSTGRES_DATABASE_URL,max:2,connectionTimeoutMillis:1000,statement_timeout:5000});
  test.beforeEach(async()=>{
    await adminPool.query("DELETE FROM setup_session_delegations");
    await adminPool.query("UPDATE founder_authorities SET scopes=ARRAY['setup:plan:execute','setup:repository'],expires_at=clock_timestamp()+interval '48 hours',revoked_at=NULL WHERE principal_id=$1",[principal]);
  });
  test.after(async()=>{await maintenancePool.end();await adminPool.end();});
}

const plan=()=>compileSetup({schema_version:0,created_at:"2026-08-14T12:00:00Z",founder:{principal_id:"founder",scopes:["events:write"],assignable_trust:["untrusted_agent"],expires_at:null},repository:{provider:"github",owner:"acme",name:"engram",default_branch:"main",permissions:["contents:read"],depends_on:[]},database:{mode:"connect_existing",target:"postgresql",depends_on:[]},participants:[],groups:[],import:{paths:[],include_history:false,depends_on:[]},welcome:{expiry_days:14,depends_on:[]}});
function fixture(now=new Date(baseTime).toISOString()){
  let current=new Date(now),sequence=0;
  const store=postgresMode?new PostgresSetupSessionStore({pool:maintenancePool}):undefined;
  const manager=new SetupSessionManager({store,authenticator:founderAuthenticator(async credential=>{assert.equal(credential,"fixture-only-founder-credential");return {principal_id:principal};}),authorityResolver:founderAuthorityResolver(async principal_id=>({principal_id,scopes:["setup:plan:execute","setup:repository"],expires_at:founderExpiry})),clock:()=>new Date(current),idFactory:kind=>kind==="session"&&postgresMode?`41000000-0000-4000-8000-${String(++sequence).padStart(12,"0")}`:`${kind}-${++sequence}`});
  return {manager,async setTime(value){current=new Date(value);if(postgresMode)await adminPool.query("UPDATE setup_session_delegations SET expires_at=CASE WHEN expires_at<=$1 THEN clock_timestamp()-interval '1 second' ELSE clock_timestamp()+interval '1 hour' END WHERE founder_principal_id=$2",[value,principal]);},async cleanup(){if(postgresMode)await adminPool.query("DELETE FROM setup_session_delegations");}};
}
const start=(manager,overrides={})=>manager.start({credential:"fixture-only-founder-credential",scopes:["setup:plan:execute"],expires_at:defaultExpiry,...overrides});
const approve=async(manager,session_id)=>{const compiled=plan();return {compiled,approval:await manager.approvePlan(session_id,compiled)};};

test("session binds authenticated founder with narrowed scopes and absolute expiry",async()=>{const {manager}=fixture(),session=await start(manager);assert.deepEqual(session,{session_id:session.session_id,status:"active",founder_principal_id:principal,scopes:["setup:plan:execute"],expires_at:defaultExpiry});assert.deepEqual(await manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:1,delegations:1,credentials:0});});
test("approved step executes only within its live session",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);assert.equal((await manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect")).status,"authorized");});
test("completion structurally removes identity, delegation, approval, and credential",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);assert.deepEqual(await manager.complete(session.session_id),{session_id:session.session_id,status:"completed",authority:false});assert.deepEqual(await manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:0,delegations:0,credentials:0});assert.deepEqual(await manager.state(session.session_id),{session_id:session.session_id,status:"completed",authority:false});assert.equal(JSON.stringify(await manager.state(session.session_id)).includes(principal),false);await assert.rejects(()=>manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_REPLAY_REFUSED");});
test("expired session refuses approved execution and leaves no identity",async()=>{const f=fixture(),session=await start(f.manager),{compiled,approval}=await approve(f.manager,session.session_id);await f.setTime(defaultExpiry);assert.deepEqual(await f.manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:0,delegations:0,credentials:0});assert.deepEqual(await f.manager.state(session.session_id),{session_id:session.session_id,status:"expired",authority:false});await assert.rejects(()=>f.manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="SESSION_EXPIRED");});
test("untouched expired delegation is swept while an untouched live session remains counted",async()=>{const f=fixture(),expired=await start(f.manager),live=await start(f.manager,{expires_at:liveExpiry});await f.setTime(defaultExpiry);assert.deepEqual(await f.manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:1,delegations:1,credentials:0});assert.deepEqual(await f.manager.state(expired.session_id),{session_id:expired.session_id,status:"expired",authority:false});assert.equal((await f.manager.state(live.session_id)).status,"active");assert.deepEqual((await f.manager.state(live.session_id)).scopes,["setup:plan:execute"]);});
test("torn-down session cannot authorize and replayed approval is refused",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);await manager.complete(session.session_id);await assert.rejects(()=>manager.authorize(session.session_id),error=>error.code==="SESSION_REVOKED");await assert.rejects(()=>manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_REPLAY_REFUSED");});
test("approval from session A cannot execute under session B",async()=>{const {manager}=fixture(),a=await start(manager),b=await start(manager),{compiled,approval}=await approve(manager,a.session_id);await assert.rejects(()=>manager.executeApprovedStep(b.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_SESSION_MISMATCH");assert.equal((await manager.executeApprovedStep(a.session_id,approval,compiled,"repository.connect")).status,"authorized");});
test("scope and expiry ceilings reuse W0 predicates",async()=>{const {manager}=fixture();await assert.rejects(()=>start(manager,{scopes:["setup:admin"]}),error=>error.code==="SESSION_SCOPE_EXCEEDS_FOUNDER");await assert.rejects(()=>start(manager,{expires_at:outlivingExpiry}),error=>error.code==="SESSION_OUTLIVES_FOUNDER");assert.equal((await start(manager,{scopes:["setup:repository"],expires_at:positiveCeilingExpiry})).status,"active");});
test("non-setup scope and unbounded session are refused",async()=>{const {manager}=fixture();await assert.rejects(()=>start(manager,{scopes:["events:write"]}),error=>error.code==="SESSION_SCOPE_NOT_SETUP");await assert.rejects(()=>start(manager,{expires_at:null}),error=>error.code==="SESSION_ABSOLUTE_EXPIRY_REQUIRED");assert.equal((await start(manager)).status,"active");});
test("abandonment leaves no partial authority",async()=>{const {manager}=fixture(),session=await start(manager),{compiled,approval}=await approve(manager,session.session_id);await manager.abandon(session.session_id);assert.deepEqual(await manager.identityInventory(),{wizard_principals:0,wizard_actors:0,session_principal_bindings:0,delegations:0,credentials:0});assert.equal((await manager.state(session.session_id)).status,"abandoned");await assert.rejects(()=>manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),error=>error.code==="APPROVAL_REPLAY_REFUSED");});
test("state machine is deterministic under injected clock and ids",async()=>{async function run(){const f=fixture(),session=await start(f.manager),{compiled,approval}=await approve(f.manager,session.session_id),authorized=await f.manager.executeApprovedStep(session.session_id,approval,compiled,"repository.connect"),ended=await f.manager.complete(session.session_id),inventory=await f.manager.identityInventory();await f.cleanup();return {session,approval,authorized,ended,inventory};}assert.deepEqual(await run(),await run());});
test("authenticator returns identity only and fixture credential is never stored",async()=>{const {manager}=fixture(),session=await start(manager);assert.equal(JSON.stringify(await manager.state(session.session_id)).includes("fixture-only-founder-credential"),false);assert.equal((await manager.identityInventory()).credentials,0);});
