import assert from "node:assert/strict";
import test from "node:test";
import { compileSetup } from "../packages/git-adapter/src/workspace-setup.mjs";

function plan(){return {schema_version:0,created_at:"2026-08-14T12:00:00Z",founder:{principal_id:"founder",scopes:["events:write"],assignable_trust:["untrusted_agent","verified_human"],expires_at:"2026-09-01T00:00:00Z"},repository:{provider:"github",owner:"acme",name:"engram",default_branch:"main",permissions:["contents:read"],depends_on:[]},database:{mode:"connect_existing",target:"postgresql",depends_on:[]},participants:[{id:"owner",kind:"human",role:"owner",scopes:["events:write"],capabilities:[],groups:[],trust:"verified_human",projects:["project-1"],expires_at:"2026-08-25T00:00:00Z",owner_id:null,depends_on:[]},{id:"agent",kind:"agent",role:"contributor",scopes:["events:write"],capabilities:[],groups:[],trust:"untrusted_agent",projects:["project-1"],expires_at:"2026-08-20T00:00:00Z",owner_id:"owner",depends_on:["participant.owner"]}],groups:[],import:{paths:[],include_history:false,depends_on:[]},welcome:{expiry_days:14,depends_on:["participant.agent"]}};}
function refused(code,mutate){const p=plan();mutate(p);assert.throws(()=>compileSetup(p),error=>error.code===code);}

test("finite founder refuses non-expiring participant; both non-expiring is positive",()=>{refused("GRANT_OUTLIVES_GRANTER",p=>{p.participants[0].expires_at=null;});const p=plan();p.founder.expires_at=null;p.participants[0].expires_at=null;assert.ok(compileSetup(p));});
test("finite owner refuses non-expiring agent; bounded agent is positive",()=>{refused("AGENT_GRANT_EXCEEDS_OWNER",p=>{p.participants[1].expires_at=null;});const p=plan();p.participants[1].expires_at=p.participants[0].expires_at;assert.ok(compileSetup(p));});
test("authorized founder assigns verified_human to human",()=>{assert.equal(compileSetup(plan()).find(s=>s.step_id==="participant.owner").parameters.trust,"verified_human");});
test("participant cannot claim trust founder cannot assign",()=>{refused("SELF_ASSERTED_TRUST_REFUSED",p=>{p.participants[1].trust="trusted_agent";});const p=plan();p.founder.assignable_trust.push("trusted_agent");p.participants[1].trust="trusted_agent";assert.ok(compileSetup(p));});
test("agent cannot receive verified_human even when founder can assign it",()=>{refused("TRUST_KIND_INCOMPATIBLE",p=>{p.participants[1].trust="verified_human";});assert.ok(compileSetup(plan()));});
test("unsupported trust elevation is refused",()=>{refused("SELF_ASSERTED_TRUST_REFUSED",p=>{p.participants[0].trust="system";});assert.ok(compileSetup(plan()));});
test("guest trust remains untrusted_agent",()=>{const p=plan();p.participants.push({id:"guest",kind:"guest",role:"contributor",scopes:["events:write"],capabilities:[],groups:[],trust:"verified_human",projects:["project-1"],expires_at:"2026-08-20T00:00:00Z",owner_id:null,depends_on:[]});assert.throws(()=>compileSetup(p),error=>error.code==="TRUST_KIND_INCOMPATIBLE");p.participants.at(-1).trust="untrusted_agent";assert.ok(compileSetup(p));});
