BEGIN;
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM pg_policies WHERE tablename='project_memberships' AND permissive='RESTRICTIVE') THEN RAISE EXCEPTION 'membership policy assumptions violated'; END IF;
END $$;
CREATE POLICY membership_principal_self ON project_memberships FOR SELECT USING (principal_id=nullif(current_setting('app.principal_id',true),'')::uuid);
CREATE OR REPLACE FUNCTION derive_mint_membership(p_principal uuid) RETURNS TABLE(tenant_id uuid,project_id uuid) LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$ SELECT pm.tenant_id,pm.project_id FROM project_memberships pm WHERE pm.principal_id=p_principal ORDER BY pm.tenant_id,pm.project_id LIMIT 1 $$;
CREATE OR REPLACE FUNCTION mint_custody_reference(p_credential_class text,p_namespace epr_namespace,p_model custody_model,p_key_locator text,p_metadata jsonb DEFAULT '{}') RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE principal uuid:=nullif(current_setting('app.principal_id',true),'')::uuid;t uuid;p uuid;g founder_authorities%ROWTYPE;canonical custody_model;row_id uuid:=gen_random_uuid();ref text;ms bigint;hexms text;required text; BEGIN IF principal IS NULL THEN RAISE EXCEPTION 'MINT_AUTHORITY_REFUSED' USING ERRCODE='42501';END IF;SELECT * INTO g FROM founder_authorities WHERE principal_id=principal FOR SHARE;IF NOT FOUND OR g.revoked_at IS NOT NULL OR g.expires_at<=clock_timestamp() THEN RAISE EXCEPTION 'MINT_AUTHORITY_REFUSED' USING ERRCODE='42501';END IF;SELECT d.tenant_id,d.project_id INTO t,p FROM derive_mint_membership(principal) d;IF t IS NULL THEN RAISE EXCEPTION 'TENANT_PROJECT_REFUSED' USING ERRCODE='42501';END IF;PERFORM set_config('app.tenant_id',t::text,true);SELECT custody_model INTO canonical FROM custody_inventory_models WHERE credential_class=p_credential_class;IF canonical IS NULL OR p_model<>canonical THEN RAISE EXCEPTION 'MODEL_DERIVATION_REFUSED' USING ERRCODE='42501';END IF;IF p_namespace IN ('shape','installation') THEN RAISE EXCEPTION 'NAMESPACE_REFUSED' USING ERRCODE='42501';END IF;required:=format('custody:mint:%s:%s:%s',p_namespace,p_credential_class,p_model);IF NOT(required=ANY(g.scopes)) THEN RAISE EXCEPTION 'SCOPE_EXCEEDED' USING ERRCODE='42501';END IF;IF p_model='B' AND p_key_locator IS NULL THEN RAISE EXCEPTION 'KEY_LOCATOR_REQUIRED';END IF;IF p_model='A' AND p_key_locator IS NOT NULL THEN RAISE EXCEPTION 'KEY_LOCATOR_FORBIDDEN';END IF;IF NOT custody_metadata_keys_allowed(p_metadata) THEN RAISE EXCEPTION 'METADATA_KEY_REFUSED';END IF;ms:=floor(extract(epoch from clock_timestamp())*1000)::bigint;hexms:=lpad(to_hex(ms),12,'0');ref:=format('epr:%s:%s-%s-7%s-8%s-%s',p_namespace,substr(hexms,1,8),substr(hexms,9,4),substr(replace(row_id::text,'-',''),1,3),substr(replace(row_id::text,'-',''),18,3),substr(replace(row_id::text,'-',''),21,12));INSERT INTO custody_rows(id,tenant_id,project_id,namespace,credential_class,custody_model,inventory_model,required_scope,key_locator,metadata,minted_by_principal_id,retention_policy) VALUES(row_id,t,p,p_namespace,p_credential_class,p_model,canonical::text,required,p_key_locator,p_metadata,principal,'RET-AUDIT-400');INSERT INTO minted_references VALUES(ref,row_id,t,p,p_namespace,clock_timestamp());INSERT INTO custody_audit(tenant_id,project_id,namespace,credential_class,action,outcome,principal_id,reference) VALUES(t,p,p_namespace,p_credential_class,'mint','success',principal,ref);RETURN ref;END $$;
REVOKE ALL ON FUNCTION mint_custody_reference(text,epr_namespace,custody_model,text,jsonb) FROM PUBLIC,engram_app;GRANT EXECUTE ON FUNCTION mint_custody_reference(text,epr_namespace,custody_model,text,jsonb) TO engram_maintenance;
COMMIT;
