import { randomUUID } from "node:crypto";

import { SetupPlanError, grantOutlives, isCompiledSetup, scopesExceed } from "./workspace-setup.mjs";
import { planMismatchError } from "./workspace-approval.mjs";

const AUTHENTICATOR=Symbol("founder-authenticator");
const AUTHORITY_RESOLVER=Symbol("founder-authority-resolver");
export function founderAuthenticator(authenticate){if(typeof authenticate!=="function")throw new TypeError("authenticate must be a function");return Object.freeze({[AUTHENTICATOR]:true,authenticate});}
export function founderAuthorityResolver(resolve){if(typeof resolve!=="function")throw new TypeError("resolve must be a function");return Object.freeze({[AUTHORITY_RESOLVER]:true,resolve});}
const setupScopesOnly=scopes=>scopes.every(scope=>scope.startsWith("setup:"));
const approvalMatches=(presented,stored)=>presented.session_id===stored.session_id&&presented.plan_digest===stored.plan_digest&&JSON.stringify(presented.steps)===JSON.stringify(stored.steps);
export class SetupSessionManager {
  #sessions=new Map();#tombstones=new Map();#revokedApprovals=new Set();#authenticator;#authorityResolver;#clock;#idFactory;
  constructor({authenticator,authorityResolver,clock=()=>new Date(),idFactory=()=>randomUUID()}={}){if(!authenticator?.[AUTHENTICATOR])throw new TypeError("founder authenticator required");if(!authorityResolver?.[AUTHORITY_RESOLVER])throw new TypeError("founder authority resolver required");this.#authenticator=authenticator;this.#authorityResolver=authorityResolver;this.#clock=clock;this.#idFactory=idFactory;}
  async start({credential,scopes,expires_at}){this.#sweepExpired();const identity=await this.#authenticator.authenticate(credential);if(!identity||Object.keys(identity).some(key=>key!=="principal_id")||typeof identity.principal_id!=="string")throw new SetupPlanError("FOUNDER_AUTHENTICATION_REFUSED","authenticated identity must contain only principal_id");const founder_authority=await this.#authorityResolver.resolve(identity.principal_id);if(!founder_authority||founder_authority.principal_id!==identity.principal_id)throw new SetupPlanError("FOUNDER_AUTHORITY_NOT_FOUND","no trusted authority for authenticated principal");if(!setupScopesOnly(scopes))throw new SetupPlanError("SESSION_SCOPE_NOT_SETUP","delegation contains non-setup scope");if(scopesExceed(scopes,founder_authority.scopes))throw new SetupPlanError("SESSION_SCOPE_EXCEEDS_FOUNDER","delegation exceeds resolved founder scopes");if(expires_at===null||!Number.isFinite(Date.parse(expires_at)))throw new SetupPlanError("SESSION_ABSOLUTE_EXPIRY_REQUIRED","session requires absolute expiry");if(grantOutlives(expires_at,founder_authority.expires_at))throw new SetupPlanError("SESSION_OUTLIVES_FOUNDER","session outlives resolved founder");if(Date.parse(expires_at)<=this.#clock().getTime())throw new SetupPlanError("SESSION_EXPIRED","session expiry is not in the future");const session_id=this.#idFactory("session"),session={session_id,status:"active",founder_principal_id:identity.principal_id,expires_at,delegation:{scopes:[...scopes],expires_at},approvals:new Map(),events:[{kind:"session.started",session_id}]};this.#sessions.set(session_id,session);return this.#public(session);}
  approvePlan(session_id,compiledPlan){const session=this.#live(session_id);if(!isCompiledSetup(compiledPlan))throw new SetupPlanError("UNCOMPILED_PLAN_REFUSED","approval requires compileSetup or loadSetupPlan output");const steps=Object.freeze(compiledPlan.map(({step_id,action_digest})=>Object.freeze({step_id,action_digest}))),approval=Object.freeze({approval_id:this.#idFactory("approval"),session_id,plan_digest:compiledPlan.plan_digest,steps});session.approvals.set(approval.approval_id,{approval,plan:compiledPlan});session.events.push({kind:"plan.approved",approval_id:approval.approval_id,plan_digest:approval.plan_digest});return approval;}
  executeApprovedStep(session_id,approval,presentedPlan,step_id){this.#sweepExpired();if(this.#tombstones.get(session_id)?.status==="expired")throw new SetupPlanError("SESSION_EXPIRED",session_id);if(this.#revokedApprovals.has(approval.approval_id))throw new SetupPlanError("APPROVAL_REPLAY_REFUSED",approval.approval_id);const session=this.#live(session_id);if(approval.session_id!==session_id)throw new SetupPlanError("APPROVAL_SESSION_MISMATCH",approval.approval_id);const stored=session.approvals.get(approval.approval_id);if(!stored||!approvalMatches(approval,stored.approval))throw new SetupPlanError("APPROVAL_NOT_FOUND",approval.approval_id);if(!isCompiledSetup(presentedPlan))throw new SetupPlanError("UNCOMPILED_PLAN_REFUSED","execution requires compileSetup or loadSetupPlan output");if(presentedPlan.plan_digest!==stored.approval.plan_digest)throw planMismatchError(stored.plan,presentedPlan);const index=presentedPlan.findIndex(step=>step.step_id===step_id),approved=stored.approval.steps[index],step=presentedPlan[index];if(index<0||!approved||approved.step_id!==step.step_id||approved.action_digest!==step.action_digest)throw new SetupPlanError("STEP_NOT_IN_APPROVED_PLAN",step_id);session.events.push({kind:"step.authorized",approval_id:approval.approval_id,step_id,index});return Object.freeze({status:"authorized",session_id,step_id,index,action_digest:step.action_digest,plan_digest:presentedPlan.plan_digest});}
  authorize(session_id){return this.#public(this.#live(session_id));}
  complete(session_id){this.#sweepExpired();return this.#teardown(session_id,"completed");}
  abandon(session_id){this.#sweepExpired();return this.#teardown(session_id,"abandoned");}
  state(session_id){this.#sweepExpired();if(this.#sessions.has(session_id))return this.#public(this.#sessions.get(session_id));return this.#tombstones.get(session_id)??null;}
  identityInventory(){this.#sweepExpired();let delegations=0;for(const session of this.#sessions.values())if(session.delegation)delegations++;return Object.freeze({wizard_principals:0,wizard_actors:0,session_principal_bindings:this.#sessions.size,delegations,credentials:0});}
  #live(session_id){this.#sweepExpired();const session=this.#sessions.get(session_id);if(!session){const tombstone=this.#tombstones.get(session_id);throw new SetupPlanError(tombstone?.status==="expired"?"SESSION_EXPIRED":"SESSION_REVOKED",session_id);}return session;}
  #sweepExpired(){const now=this.#clock().getTime();for(const [session_id,session] of this.#sessions)if(now>=Date.parse(session.expires_at))this.#teardown(session_id,"expired");}
  #teardown(session_id,status){const session=this.#sessions.get(session_id);if(!session)throw new SetupPlanError("SESSION_REVOKED",session_id);for(const id of session.approvals.keys())this.#revokedApprovals.add(id);this.#sessions.delete(session_id);const tombstone=Object.freeze({session_id,status,authority:false});this.#tombstones.set(session_id,tombstone);return tombstone;}
  #public(session){return Object.freeze({session_id:session.session_id,status:session.status,founder_principal_id:session.founder_principal_id,scopes:Object.freeze([...session.delegation.scopes]),expires_at:session.expires_at});}
}
