import { randomUUID } from "node:crypto";

import { SetupPlanError, grantOutlives, isCompiledSetup, scopesExceed } from "./workspace-setup.mjs";

const AUTHENTICATOR=Symbol("founder-authenticator");
export function founderAuthenticator(authenticate){if(typeof authenticate!=="function")throw new TypeError("authenticate must be a function");return Object.freeze({[AUTHENTICATOR]:true,authenticate});}
const setupScopesOnly=scopes=>scopes.every(scope=>scope.startsWith("setup:"));
export class SetupSessionManager {
  #sessions=new Map();#tombstones=new Map();#revokedApprovals=new Set();#authenticator;#clock;#idFactory;
  constructor({authenticator,clock=()=>new Date(),idFactory=()=>randomUUID()}={}){if(!authenticator?.[AUTHENTICATOR])throw new TypeError("founder authenticator required");this.#authenticator=authenticator;this.#clock=clock;this.#idFactory=idFactory;}
  async start({credential,founder_authority,scopes,expires_at}){const identity=await this.#authenticator.authenticate(credential);if(!identity||Object.keys(identity).some(key=>key!=="principal_id")||identity.principal_id!==founder_authority.principal_id)throw new SetupPlanError("FOUNDER_AUTHENTICATION_REFUSED","authenticated principal mismatch");if(!setupScopesOnly(scopes))throw new SetupPlanError("SESSION_SCOPE_NOT_SETUP","delegation contains non-setup scope");if(scopesExceed(scopes,founder_authority.scopes))throw new SetupPlanError("SESSION_SCOPE_EXCEEDS_FOUNDER","delegation exceeds founder scopes");if(expires_at===null||!Number.isFinite(Date.parse(expires_at)))throw new SetupPlanError("SESSION_ABSOLUTE_EXPIRY_REQUIRED","session requires absolute expiry");if(grantOutlives(expires_at,founder_authority.expires_at))throw new SetupPlanError("SESSION_OUTLIVES_FOUNDER","session outlives founder");if(Date.parse(expires_at)<=this.#clock().getTime())throw new SetupPlanError("SESSION_EXPIRED","session expiry is not in the future");const session_id=this.#idFactory("session"),session={session_id,status:"active",founder_principal_id:identity.principal_id,expires_at,delegation:{scopes:[...scopes],expires_at},approvals:new Map(),events:[{kind:"session.started",session_id}]};this.#sessions.set(session_id,session);return this.#public(session);}
  approveStep(session_id,compiledPlan,step_id){const session=this.#live(session_id);if(!isCompiledSetup(compiledPlan))throw new SetupPlanError("UNCOMPILED_PLAN_REFUSED","approval requires compileSetup output");const step=compiledPlan.find(item=>item.step_id===step_id);if(!step)throw new SetupPlanError("STEP_NOT_IN_PLAN",step_id);const approval={approval_id:this.#idFactory("approval"),session_id,step_id,action_digest:step.action_digest??null};session.approvals.set(approval.approval_id,approval);session.events.push({kind:"step.approved",approval_id:approval.approval_id,step_id});return Object.freeze({...approval});}
  executeApprovedStep(session_id,approval){if(this.#revokedApprovals.has(approval.approval_id))throw new SetupPlanError("APPROVAL_REPLAY_REFUSED",approval.approval_id);const session=this.#live(session_id);if(approval.session_id!==session_id)throw new SetupPlanError("APPROVAL_SESSION_MISMATCH",approval.approval_id);const stored=session.approvals.get(approval.approval_id);if(!stored||stored.step_id!==approval.step_id||stored.action_digest!==approval.action_digest)throw new SetupPlanError("APPROVAL_NOT_FOUND",approval.approval_id);session.events.push({kind:"step.authorized",approval_id:approval.approval_id,step_id:approval.step_id});return Object.freeze({status:"authorized",session_id,step_id:approval.step_id,action_digest:approval.action_digest});}
  authorize(session_id){return this.#public(this.#live(session_id));}
  complete(session_id){return this.#teardown(session_id,"completed");}
  abandon(session_id){return this.#teardown(session_id,"abandoned");}
  state(session_id){if(this.#sessions.has(session_id))return this.#public(this.#sessions.get(session_id));return this.#tombstones.get(session_id)??null;}
  identityInventory(){let delegations=0;for(const session of this.#sessions.values())if(session.delegation)delegations++;return Object.freeze({wizard_principals:0,wizard_actors:0,session_principal_bindings:this.#sessions.size,delegations,credentials:0});}
  #live(session_id){const session=this.#sessions.get(session_id);if(!session){const tombstone=this.#tombstones.get(session_id);throw new SetupPlanError(tombstone?.status==="expired"?"SESSION_EXPIRED":"SESSION_REVOKED",session_id);}if(this.#clock().getTime()>=Date.parse(session.expires_at)){this.#teardown(session_id,"expired");throw new SetupPlanError("SESSION_EXPIRED",session_id);}return session;}
  #teardown(session_id,status){const session=this.#sessions.get(session_id);if(!session)throw new SetupPlanError("SESSION_REVOKED",session_id);for(const id of session.approvals.keys())this.#revokedApprovals.add(id);this.#sessions.delete(session_id);const tombstone=Object.freeze({session_id,status,authority:false});this.#tombstones.set(session_id,tombstone);return tombstone;}
  #public(session){return Object.freeze({session_id:session.session_id,status:session.status,founder_principal_id:session.founder_principal_id,scopes:Object.freeze([...session.delegation.scopes]),expires_at:session.expires_at});}
}
